//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Client.OnlineReceptionImplService
{
     
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hotelserver.group.hotel.com/")]
    public partial class BadRequestException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hotelserver.group.hotel.com/")]
    public partial class room
    {
        
        private string roomNumberField;
        
        private int floorNumberField;
        
        private bool hasDoubleBedField;
        
        private int numberOfSingleBedsField;
        
        private double roomSizeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string roomNumber
        {
            get
            {
                return this.roomNumberField;
            }
            set
            {
                this.roomNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int floorNumber
        {
            get
            {
                return this.floorNumberField;
            }
            set
            {
                this.floorNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool hasDoubleBed
        {
            get
            {
                return this.hasDoubleBedField;
            }
            set
            {
                this.hasDoubleBedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int numberOfSingleBeds
        {
            get
            {
                return this.numberOfSingleBedsField;
            }
            set
            {
                this.numberOfSingleBedsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double roomSize
        {
            get
            {
                return this.roomSizeField;
            }
            set
            {
                this.roomSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hotelserver.group.hotel.com/")]
    public partial class reservation
    {
        
        private int numberField;
        
        private System.DateTime fromField;
        
        private bool fromFieldSpecified;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        private room[] roomsField;
        
        private int ownersIdField;
        
        private string notesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromSpecified
        {
            get
            {
                return this.fromFieldSpecified;
            }
            set
            {
                this.fromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toSpecified
        {
            get
            {
                return this.toFieldSpecified;
            }
            set
            {
                this.toFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rooms", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public room[] rooms
        {
            get
            {
                return this.roomsField;
            }
            set
            {
                this.roomsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int ownersId
        {
            get
            {
                return this.ownersIdField;
            }
            set
            {
                this.ownersIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hotelserver.group.hotel.com/")]
    public partial class InvalidCredentialsException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hotelserver.group.hotel.com/")]
    public partial class DocumentException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hotelserver.group.hotel.com/", ConfigurationName="Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl")]
    public interface OnlineReceptionImpl
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/getReservationsRequest", ReplyAction="http://hotelserver.group.hotel.com/OnlineReceptionImpl/getReservationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.getReservationsResponse> getReservationsAsync(Hotel_Client.OnlineReceptionImplService.getReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/makeReservationRequest", ReplyAction="http://hotelserver.group.hotel.com/OnlineReceptionImpl/makeReservationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hotel_Client.OnlineReceptionImplService.BadRequestException), Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/makeReservation/Fault/BadR" +
            "equestException", Name="BadRequestException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.makeReservationResponse> makeReservationAsync(Hotel_Client.OnlineReceptionImplService.makeReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/loginRequest", ReplyAction="http://hotelserver.group.hotel.com/OnlineReceptionImpl/loginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hotel_Client.OnlineReceptionImplService.InvalidCredentialsException), Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/login/Fault/InvalidCredent" +
            "ialsException", Name="InvalidCredentialsException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.loginResponse> loginAsync(Hotel_Client.OnlineReceptionImplService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/cancelReservationRequest", ReplyAction="http://hotelserver.group.hotel.com/OnlineReceptionImpl/cancelReservationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hotel_Client.OnlineReceptionImplService.BadRequestException), Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/cancelReservation/Fault/Ba" +
            "dRequestException", Name="BadRequestException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.cancelReservationResponse> cancelReservationAsync(Hotel_Client.OnlineReceptionImplService.cancelReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/modifyReservationRequest", ReplyAction="http://hotelserver.group.hotel.com/OnlineReceptionImpl/modifyReservationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hotel_Client.OnlineReceptionImplService.BadRequestException), Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/modifyReservation/Fault/Ba" +
            "dRequestException", Name="BadRequestException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.modifyReservationResponse> modifyReservationAsync(Hotel_Client.OnlineReceptionImplService.modifyReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/requestReservationConfirma" +
            "tionRequest", ReplyAction="http://hotelserver.group.hotel.com/OnlineReceptionImpl/requestReservationConfirma" +
            "tionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hotel_Client.OnlineReceptionImplService.BadRequestException), Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/requestReservationConfirma" +
            "tion/Fault/BadRequestException", Name="BadRequestException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hotel_Client.OnlineReceptionImplService.DocumentException), Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/requestReservationConfirma" +
            "tion/Fault/DocumentException", Name="DocumentException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.requestReservationConfirmationResponse> requestReservationConfirmationAsync(Hotel_Client.OnlineReceptionImplService.requestReservationConfirmationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/getAvailableRoomsRequest", ReplyAction="http://hotelserver.group.hotel.com/OnlineReceptionImpl/getAvailableRoomsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hotel_Client.OnlineReceptionImplService.BadRequestException), Action="http://hotelserver.group.hotel.com/OnlineReceptionImpl/getAvailableRooms/Fault/Ba" +
            "dRequestException", Name="BadRequestException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.getAvailableRoomsResponse> getAvailableRoomsAsync(Hotel_Client.OnlineReceptionImplService.getAvailableRoomsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReservations", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class getReservationsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getReservationsRequest()
        {
        }
        
        public getReservationsRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReservationsResponse", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class getReservationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Hotel_Client.OnlineReceptionImplService.reservation[] @return;
        
        public getReservationsResponse()
        {
        }
        
        public getReservationsResponse(Hotel_Client.OnlineReceptionImplService.reservation[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="makeReservation", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class makeReservationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg4;
        
        public makeReservationRequest()
        {
        }
        
        public makeReservationRequest(string[] arg0, string arg1, string arg2, string arg3, int arg4)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="makeReservationResponse", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class makeReservationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public makeReservationResponse()
        {
        }
        
        public makeReservationResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public loginRequest()
        {
        }
        
        public loginRequest(string arg0, string arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public loginResponse()
        {
        }
        
        public loginResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelReservation", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class cancelReservationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public cancelReservationRequest()
        {
        }
        
        public cancelReservationRequest(int arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelReservationResponse", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class cancelReservationResponse
    {
        
        public cancelReservationResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hotelserver.group.hotel.com/")]
    public partial class modifiedReservation
    {
        
        private int numberField;
        
        private string fromField;
        
        private string toField;
        
        private room[] roomsField;
        
        private int ownersIdField;
        
        private string notesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rooms", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public room[] rooms
        {
            get
            {
                return this.roomsField;
            }
            set
            {
                this.roomsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int ownersId
        {
            get
            {
                return this.ownersIdField;
            }
            set
            {
                this.ownersIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyReservation", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class modifyReservationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Hotel_Client.OnlineReceptionImplService.modifiedReservation arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public modifyReservationRequest()
        {
        }
        
        public modifyReservationRequest(Hotel_Client.OnlineReceptionImplService.modifiedReservation arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyReservationResponse", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class modifyReservationResponse
    {
        
        public modifyReservationResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="requestReservationConfirmation", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class requestReservationConfirmationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public requestReservationConfirmationRequest()
        {
        }
        
        public requestReservationConfirmationRequest(int arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="requestReservationConfirmationResponse", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class requestReservationConfirmationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public requestReservationConfirmationResponse()
        {
        }
        
        public requestReservationConfirmationResponse(byte[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAvailableRooms", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class getAvailableRoomsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getAvailableRoomsRequest()
        {
        }
        
        public getAvailableRoomsRequest(string arg0, string arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAvailableRoomsResponse", WrapperNamespace="http://hotelserver.group.hotel.com/", IsWrapped=true)]
    public partial class getAvailableRoomsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hotelserver.group.hotel.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Hotel_Client.OnlineReceptionImplService.room[] @return;
        
        public getAvailableRoomsResponse()
        {
        }
        
        public getAvailableRoomsResponse(Hotel_Client.OnlineReceptionImplService.room[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface OnlineReceptionImplChannel : Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class OnlineReceptionImplClient : System.ServiceModel.ClientBase<Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl>, Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OnlineReceptionImplClient() : 
                base(OnlineReceptionImplClient.GetDefaultBinding(), OnlineReceptionImplClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OnlineReceptionImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineReceptionImplClient(EndpointConfiguration endpointConfiguration) : 
                base(OnlineReceptionImplClient.GetBindingForEndpoint(endpointConfiguration), OnlineReceptionImplClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineReceptionImplClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OnlineReceptionImplClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineReceptionImplClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OnlineReceptionImplClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineReceptionImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.getReservationsResponse> Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl.getReservationsAsync(Hotel_Client.OnlineReceptionImplService.getReservationsRequest request)
        {
            return base.Channel.getReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.getReservationsResponse> getReservationsAsync(int arg0)
        {
            Hotel_Client.OnlineReceptionImplService.getReservationsRequest inValue = new Hotel_Client.OnlineReceptionImplService.getReservationsRequest();
            inValue.arg0 = arg0;
            return ((Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl)(this)).getReservationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.makeReservationResponse> Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl.makeReservationAsync(Hotel_Client.OnlineReceptionImplService.makeReservationRequest request)
        {
            return base.Channel.makeReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.makeReservationResponse> makeReservationAsync(string[] arg0, string arg1, string arg2, string arg3, int arg4)
        {
            Hotel_Client.OnlineReceptionImplService.makeReservationRequest inValue = new Hotel_Client.OnlineReceptionImplService.makeReservationRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl)(this)).makeReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.loginResponse> Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl.loginAsync(Hotel_Client.OnlineReceptionImplService.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.loginResponse> loginAsync(string arg0, string arg1)
        {
            Hotel_Client.OnlineReceptionImplService.loginRequest inValue = new Hotel_Client.OnlineReceptionImplService.loginRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.cancelReservationResponse> Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl.cancelReservationAsync(Hotel_Client.OnlineReceptionImplService.cancelReservationRequest request)
        {
            return base.Channel.cancelReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.cancelReservationResponse> cancelReservationAsync(int arg0, int arg1)
        {
            Hotel_Client.OnlineReceptionImplService.cancelReservationRequest inValue = new Hotel_Client.OnlineReceptionImplService.cancelReservationRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl)(this)).cancelReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.modifyReservationResponse> Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl.modifyReservationAsync(Hotel_Client.OnlineReceptionImplService.modifyReservationRequest request)
        {
            return base.Channel.modifyReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.modifyReservationResponse> modifyReservationAsync(Hotel_Client.OnlineReceptionImplService.modifiedReservation arg0, int arg1)
        {
            Hotel_Client.OnlineReceptionImplService.modifyReservationRequest inValue = new Hotel_Client.OnlineReceptionImplService.modifyReservationRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl)(this)).modifyReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.requestReservationConfirmationResponse> Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl.requestReservationConfirmationAsync(Hotel_Client.OnlineReceptionImplService.requestReservationConfirmationRequest request)
        {
            return base.Channel.requestReservationConfirmationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.requestReservationConfirmationResponse> requestReservationConfirmationAsync(int arg0, int arg1)
        {
            Hotel_Client.OnlineReceptionImplService.requestReservationConfirmationRequest inValue = new Hotel_Client.OnlineReceptionImplService.requestReservationConfirmationRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl)(this)).requestReservationConfirmationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.getAvailableRoomsResponse> Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl.getAvailableRoomsAsync(Hotel_Client.OnlineReceptionImplService.getAvailableRoomsRequest request)
        {
            return base.Channel.getAvailableRoomsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotel_Client.OnlineReceptionImplService.getAvailableRoomsResponse> getAvailableRoomsAsync(string arg0, string arg1)
        {
            Hotel_Client.OnlineReceptionImplService.getAvailableRoomsRequest inValue = new Hotel_Client.OnlineReceptionImplService.getAvailableRoomsRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((Hotel_Client.OnlineReceptionImplService.OnlineReceptionImpl)(this)).getAvailableRoomsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OnlineReceptionImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.MessageEncoding = System.ServiceModel.WSMessageEncoding.Mtom;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OnlineReceptionImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/HotelServer-1.0-SNAPSHOT/OnlineReceptionImplService");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OnlineReceptionImplClient.GetBindingForEndpoint(EndpointConfiguration.OnlineReceptionImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OnlineReceptionImplClient.GetEndpointAddress(EndpointConfiguration.OnlineReceptionImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            OnlineReceptionImplPort,
        }
    }
}
